[project]
name = "litellm-proxy-extras"
version = "0.4.60"
description = "Additional files for the LiteLLM Proxy. Reduces the size of the main litellm package."
authors = [{name = "BerriAI"}]
readme = "README.md"
requires-python = ">=3.8.1,<4.0,!=3.9.7"

# Add any specific runtime dependencies for proxy-extras here
dependencies = []

[project.urls]
homepage = "https://litellm.ai"
repository = "https://github.com/BerriAI/litellm"
documentation = "https://docs.litellm.ai"

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

# Exclude old build artifacts from the source distribution
[tool.hatch.build]
exclude = [
    "dist",
]

# Explicitly declare the Python module to bundle into the compiled wheel (.whl).
# Hatchling will natively include the Prisma SQL migration files within this directory.
[tool.hatch.build.targets.wheel]
packages = [
    "litellm_proxy_extras"
]

[tool.commitizen]
version = "0.4.60"
version_files = [
    "pyproject.toml:^version",
    "../requirements.txt:litellm-proxy-extras==",
    "../pyproject.toml:litellm-proxy-extras>="
]
